"""first

Revision ID: f164e01304f0
Revises: 4a4292939350
Create Date: 2023-07-09 16:03:50.933824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f164e01304f0"
down_revision = "4a4292939350"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notice",
        sa.Column("notice_num", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("member_num", sa.Integer(), nullable=False),
        sa.Column("notice_title", sa.String(length=128), nullable=False),
        sa.Column("notice_contents", sa.String(length=512), nullable=False),
        sa.Column("notice_create_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_num"],
            ["shop_members.member_num"],
        ),
        sa.PrimaryKeyConstraint("notice_num"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notice")
    # ### end Alembic commands ###
