"""first

Revision ID: 2945e3f7547a
Revises: 40f5c93b8861
Create Date: 2023-07-09 17:04:37.641615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2945e3f7547a"
down_revision = "40f5c93b8861"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_items_categories",
        sa.Column(
            "item_category_num", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("item_category_main_name", sa.String(length=20), nullable=False),
        sa.Column("item_ctegory_sub_name", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("item_category_num"),
    )
    op.create_table(
        "shop_likes",
        sa.Column("member_num", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_num"],
            ["shop_members.member_num"],
        ),
        sa.PrimaryKeyConstraint("member_num"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shop_likes")
    op.drop_table("shop_items_categories")
    # ### end Alembic commands ###
