"""first

Revision ID: c0f486604e97
Revises: 98ed76359979
Create Date: 2023-07-09 16:32:01.200246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c0f486604e97"
down_revision = "98ed76359979"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_question_boards",
        sa.Column("board_num", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("board_categorie_num", sa.Integer(), nullable=False),
        sa.Column("member_num", sa.Integer(), nullable=False),
        sa.Column("board_create_date", sa.DateTime(), nullable=False),
        sa.Column("board_title", sa.String(length=128), nullable=False),
        sa.Column("board_contests", sa.String(length=512), nullable=False),
        sa.Column("board_is_answered", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["board_categorie_num"],
            ["shop_board_categories.board_categorie_num"],
        ),
        sa.ForeignKeyConstraint(
            ["member_num"],
            ["shop_members.member_num"],
        ),
        sa.PrimaryKeyConstraint("board_num"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shop_question_boards")
    # ### end Alembic commands ###
