"""first

Revision ID: fea69741a2dc
Revises: 0662a3d9accc
Create Date: 2023-07-09 21:20:23.750024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fea69741a2dc"
down_revision = "0662a3d9accc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
