"""first

Revision ID: c323e2d70744
Revises: fea69741a2dc
Create Date: 2023-07-09 21:26:55.006075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c323e2d70744"
down_revision = "fea69741a2dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_reviews",
        sa.Column("review_num", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_product_num", sa.Integer(), nullable=False),
        sa.Column("item_num", sa.Integer(), nullable=False),
        sa.Column("review_star", sa.Integer(), nullable=False),
        sa.Column("review_title", sa.String(length=128), nullable=False),
        sa.Column("review_contents", sa.String(length=512), nullable=False),
        sa.Column("review_create_date", sa.DateTime(), nullable=False),
        sa.Column("review_image", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_num"],
            ["shop_items.item_num"],
        ),
        sa.ForeignKeyConstraint(
            ["order_product_num"],
            ["shop_order_products.order_product_num"],
        ),
        sa.PrimaryKeyConstraint("review_num"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shop_reviews")
    # ### end Alembic commands ###
