"""first

Revision ID: 6b720dff1d3c
Revises: 2945e3f7547a
Create Date: 2023-07-09 17:05:22.091953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6b720dff1d3c"
down_revision = "2945e3f7547a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
