"""first

Revision ID: d4cc51047b48
Revises: 208e29c42b2f
Create Date: 2023-07-09 17:55:26.413741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d4cc51047b48"
down_revision = "208e29c42b2f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_item_options",
        sa.Column("item_option_num", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_num", sa.Integer(), nullable=False),
        sa.Column("item_option_color", sa.String(length=10), nullable=False),
        sa.Column("item_option_size", sa.String(length=5), nullable=False),
        sa.Column("item_option_soldout", sa.Boolean(), nullable=False),
        sa.Column("item_option_is_discount", sa.Boolean(), nullable=False),
        sa.Column("item_option_discount_price", sa.Integer(), nullable=False),
        sa.Column("item_option_discount_start_date", sa.DateTime(), nullable=False),
        sa.Column("item_option_discount_end_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_num"],
            ["shop_items.item_num"],
        ),
        sa.PrimaryKeyConstraint("item_option_num"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shop_item_options")
    # ### end Alembic commands ###
