"""first

Revision ID: 88003fcbbf5a
Revises: d4cc51047b48
Create Date: 2023-07-09 20:35:01.190173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "88003fcbbf5a"
down_revision = "d4cc51047b48"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_carts",
        sa.Column("member_num", sa.Integer(), nullable=False),
        sa.Column("item_option_num", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_option_num"],
            ["shop_item_options.item_option_num"],
        ),
        sa.ForeignKeyConstraint(
            ["member_num"],
            ["shop_items.item_num"],
        ),
        sa.PrimaryKeyConstraint("member_num"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shop_carts")
    # ### end Alembic commands ###
