"""first

Revision ID: 40f5c93b8861
Revises: c0f486604e97
Create Date: 2023-07-09 16:33:30.152221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "40f5c93b8861"
down_revision = "c0f486604e97"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_board_comments",
        sa.Column("board_num", sa.Integer(), nullable=False),
        sa.Column("member_num", sa.Integer(), nullable=False),
        sa.Column("comment_title", sa.String(length=128), nullable=False),
        sa.Column("comment_content", sa.String(length=512), nullable=False),
        sa.Column("comment_create_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["board_num"],
            ["shop_board_categories.board_categorie_num"],
        ),
        sa.ForeignKeyConstraint(
            ["member_num"],
            ["shop_members.member_num"],
        ),
        sa.PrimaryKeyConstraint("board_num"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shop_board_comments")
    # ### end Alembic commands ###
