"""first

Revision ID: 0ee4b585402a
Revises: 6b720dff1d3c
Create Date: 2023-07-09 17:05:55.152441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0ee4b585402a"
down_revision = "6b720dff1d3c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_item_categories",
        sa.Column(
            "item_category_num", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("item_category_main_name", sa.String(length=20), nullable=False),
        sa.Column("item_ctegory_sub_name", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("item_category_num"),
    )
    op.create_table(
        "shop_items",
        sa.Column("item_num", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_category_num", sa.Integer(), nullable=False),
        sa.Column("item_name", sa.String(length=20), nullable=False),
        sa.Column("item_description", sa.Text(), nullable=False),
        sa.Column("item_price", sa.Integer(), nullable=False),
        sa.Column("item_discount_price", sa.Integer(), nullable=False),
        sa.Column("item_create_date", sa.DateTime(), nullable=False),
        sa.Column("item_soldout", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_category_num"],
            ["shop_item_categories.item_category_num"],
        ),
        sa.PrimaryKeyConstraint("item_num"),
    )
    op.drop_table("shop_items_categories")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_items_categories",
        sa.Column(
            "item_category_num", mysql.INTEGER(), autoincrement=True, nullable=False
        ),
        sa.Column("item_category_main_name", mysql.VARCHAR(length=20), nullable=False),
        sa.Column("item_ctegory_sub_name", mysql.VARCHAR(length=20), nullable=False),
        sa.PrimaryKeyConstraint("item_category_num"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("shop_items")
    op.drop_table("shop_item_categories")
    # ### end Alembic commands ###
