"""first

Revision ID: bca632b19251
Revises: 9806609e4458
Create Date: 2023-07-08 23:14:29.117696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca632b19251'
down_revision = '9806609e4458'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_address',
    sa.Column('member_num', sa.Integer(), nullable=False),
    sa.Column('member_default_address', sa.String(length=256), nullable=False),
    sa.Column('member_address_1', sa.String(length=256), nullable=False),
    sa.Column('member_address_2', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['member_num'], ['shop_members.member_num'], ),
    sa.PrimaryKeyConstraint('member_num')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_address')
    # ### end Alembic commands ###
