"""first

Revision ID: 208e29c42b2f
Revises: 08306670a6f0
Create Date: 2023-07-09 17:10:52.068432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "208e29c42b2f"
down_revision = "08306670a6f0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shop_likes", sa.Column("item_num", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "shop_likes", "shop_items", ["item_num"], ["item_num"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "shop_likes", type_="foreignkey")
    op.drop_column("shop_likes", "item_num")
    # ### end Alembic commands ###
